name: iOS-ipa-build

on:
  push:
    branches:
      - '**'

jobs:
  build-ios:
    name: "🎉 iOS Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build .app (no code sign)
        run: |
          xcodebuild -project MyTimeApp.xcodeproj \
            -scheme MyTimeApp \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Package .app into Payload
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/MyTimeApp.app Payload/

      - name: Create IPA
        run: zip -r MyTimeApp.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyTimeApp-ipa
          path: MyTimeApp.ipa 